version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: mono-db
    environment:
      POSTGRES_DB: mono_db
      POSTGRES_USER: mono_user
      POSTGRES_PASSWORD: mono_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Improved logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:
